CREATE TABLE IF NOT EXISTS versions (
id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
minor integer NOT NULL,
major integer NOT NULL,
build integer NOT NULL,
released date default NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS versions_description (
id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
version_id integer NOT NULL,
descrption text NOT NULL,
PRIMARY KEY (id)
);

