version: '3.7'
services:
  postgres_slave:
    container_name: postgres_slave_cont
    image: "postgres:15"
    restart: 'no'
    extra_hosts:
      - master.host:10.18.13.2
    environment:
      - POSTGRES_DB=version_db
      - POSTGRES_USER=version_user
      - POSTGRES_PASSWORD=version_password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data    
      - ./start_db_script:/docker-entrypoint-initdb.d/
      - type: bind
        source: postgresql.conf
        target: /var/lib/postgresql/data/postgresql.conf
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    ports:
      - 5545:5432
        

    networks:
      default:
        ipv4_address: 10.18.13.3
 
     
networks:
  default:
    external: true
    name: postgres
