version: '3.7'
services:
  postgres_slave:
    container_name: postgres_slave_cont
    image: "postgres:15"
    restart: 'unless-stopped'
    extra_hosts:
      - master.host:10.18.13.2
    environment:
      - POSTGRES_DB=version_db
      - POSTGRES_USER=version_user
      - POSTGRES_PASSWORD=version_password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data    
    command: |
      bash -c "
      until pg_isready -h 10.18.13.2 -U rep_user; do
        echo 'Waiting for master...';
        sleep 5;
      done;
      if [ ! -f /var/lib/postgresql/data/standby.signal ]; then
        echo 'Master is ready. Taking base backup...';
        rm -rf /var/lib/postgresql/data/*;
        export PGPASSWORD='123' && pg_basebackup -h 10.18.13.2 -U rep_user -D /var/lib/postgresql/data -Fp -Xs -R;
        echo 'Backup complete. Starting PostgreSQL as standby...';
      fi
      exec docker-entrypoint.sh postgres -c 'hot_standby=on'
      "
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    ports:
      - 5545:5432
    networks:
      default:
        ipv4_address: 10.18.13.3
 
     
networks:
  default:
    external: true
    name: postgres
      